QuanLyQuanAn/QuanLyQuanAn2/Controllers/GioHangController.cs
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyQuanAn2.Controllers
{
    public class GioHangController : Controller
    {
        // GET: GioHang
        //[Authorize(Roles = "kh")]
        public ActionResult Index()
        {
            //Viewbag
            bool isKHDaDangNhap = false;
            if (this.HttpContext.User.Identity.IsAuthenticated)
            {
                if (AccountModel.GetLoaiUser(this.HttpContext.User.Identity.Name) == "kh")
                    isKHDaDangNhap = true;
            }
            ViewBag.IsKhachHangDaDangNhap = isKHDaDangNhap;

            //Model
            var ctGioHang = new CT_GioHangModel();
            var model = ctGioHang.GetAllByTaiKhoan(this.HttpContext.User.Identity.Name);

            return View(model);
        }

        // GET: GioHang/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: GioHang/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GioHang/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GioHang/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: GioHang/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GioHang/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: GioHang/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

QuanLyQuanAn/QuanLyQuanAn2/Controllers/GioiThieuController.cs
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyQuanAn2.Controllers
{
    public class GioiThieuController : Controller
    {
        // GET: GioiThieu
        public ActionResult Index()
        {
            //Viewbag
            bool isKHDaDangNhap = false;
            if (this.HttpContext.User.Identity.IsAuthenticated)
            {
                if (AccountModel.GetLoaiUser(this.HttpContext.User.Identity.Name) == "kh")
                    isKHDaDangNhap = true;
            }
            ViewBag.IsKhachHangDaDangNhap = isKHDaDangNhap;
            return View();
        }

        // GET: GioiThieu/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: GioiThieu/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GioiThieu/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GioiThieu/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: GioiThieu/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GioiThieu/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: GioiThieu/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

QuanLyQuanAn/QuanLyQuanAn2/Controllers/MenuSanPhamController.cs
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyQuanAn2.Controllers
{
    public class MenuSanPhamController : Controller
    {
        // GET: MenuBanHang
        public ActionResult Index()
        {
            var menu = new MenuMonAnModel();
            var model = menu.ListAll();
            bool isKHDaDangNhap = false;
            if (this.HttpContext.User.Identity.IsAuthenticated)
            {
                if (AccountModel.GetLoaiUser(this.HttpContext.User.Identity.Name) == "kh")
                    isKHDaDangNhap = true;
            }
            ViewBag.IsKhachHangDaDangNhap = isKHDaDangNhap;
            return View(model);
        }

        // GET: MenuBanHang/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MenuBanHang/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MenuBanHang/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MenuBanHang/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MenuBanHang/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MenuBanHang/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MenuBanHang/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

QuanLyQuanAn/QuanLyQuanAn2/Controllers/ThongTinCaNhanController.cs
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyQuanAn2.Controllers
{
    //[Authorize(Roles = "kh")]
    public class ThongTinCaNhanController : Controller
    {
        // GET: ThongTinCaNhan

        public ActionResult Index()
        {
            //Viewbag
            bool isKHDaDangNhap = false;
            if (this.HttpContext.User.Identity.IsAuthenticated)
            {
                if (AccountModel.GetLoaiUser(this.HttpContext.User.Identity.Name) == "kh")
                    isKHDaDangNhap = true;
            }
            ViewBag.IsKhachHangDaDangNhap = isKHDaDangNhap;

            //Model
            var khachhangipl = new KhachHangModel();
            var maKH = new AccountModel().GetID(HttpContext.User.Identity.Name);
            var model = khachhangipl.GetByMaKhachHang(maKH);
            return View(model);
        }

        // GET: ThongTinCaNhan/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ThongTinCaNhan/Create
        public ActionResult EditPassword()
        {
            //Viewbag
            bool isKHDaDangNhap = false;
            if (this.HttpContext.User.Identity.IsAuthenticated)
            {
                if (AccountModel.GetLoaiUser(this.HttpContext.User.Identity.Name) == "kh")
                    isKHDaDangNhap = true;
            }
            ViewBag.IsKhachHangDaDangNhap = isKHDaDangNhap;
            ViewBag.TenDangNhap = this.HttpContext.User.Identity.Name;
            return View();
        }

        // POST: ThongTinCaNhan/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ThongTinCaNhan/Edit/5
        public ActionResult Edit()
        {
            //Viewbag
            bool isKHDaDangNhap = false;
            if (this.HttpContext.User.Identity.IsAuthenticated)
            {
                if (AccountModel.GetLoaiUser(this.HttpContext.User.Identity.Name) == "kh")
                    isKHDaDangNhap = true;
            }
            ViewBag.IsKhachHangDaDangNhap = isKHDaDangNhap;

            //Model
            var khachhangipl = new KhachHangModel();
            var maKH = new AccountModel().GetID(HttpContext.User.Identity.Name);
            var model = khachhangipl.GetByMaKhachHang(maKH);
            return View(model);
        }

        // POST: ThongTinCaNhan/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ThongTinCaNhan/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ThongTinCaNhan/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

QuanLyQuanAn/QuanLyQuanAn2/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Quán cơm Bầu Bí</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/Assets/khachhang/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/khachhang/css/animate.css">

    <link rel="stylesheet" href="~/Assets/khachhang/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Assets/khachhang/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Assets/khachhang/css/magnific-popup.css">

    <link rel="stylesheet" href="~/Assets/khachhang/css/aos.css">

    <link rel="stylesheet" href="~/Assets/khachhang/css/ionicons.min.css">

    <link rel="stylesheet" href="~/Assets/khachhang/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/Assets/khachhang/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/Assets/khachhang/css/flaticon.css">
    <link rel="stylesheet" href="~/Assets/khachhang/css/icomoon.css">
    <link rel="stylesheet" href="~/Assets/khachhang/css/style.css">
</head>
<body class="goto-here">
    <div class="py-1 bg-primary">
        <div class="container">
            <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
                <div class="col-lg-12 d-block">
                    <div class="row d-flex">
                        <div class="col-md pr-4 d-flex topper align-items-center">
                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
                            <span class="text">093 8099 440</span>
                        </div>
                        <div class="col-md pr-4 d-flex topper align-items-center">
                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
                            <span class="text">quancombaubi@gmail.com</span>
                        </div>
                        <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
                            <span class="text">Bầu Bí - Hương vị quê nhà</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")" style="font-family:Calibri">Quán cơm Bầu Bí</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active"><a href="@Url.Action("Index", "Home")" class="nav-link">Trang chủ</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index","MenuSanPham")" class="nav-link">Menu sản phẩm</a></li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Đơn hàng của tôi</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            <a class="dropdown-item" href="@Url.Action("Index","GioHang")">Giỏ hàng</a>
                            <a class="dropdown-item" href="@Url.Action("Index","DonDatHangCuaToi",new {id=1})">Đơn hàng của tôi</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Về chúng tôi</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            <a class="dropdown-item" href="@Url.Action("Index","GioiThieu")">Giới thiệu</a>

                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cá nhân</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            <a class="dropdown-item" href="@Url.Action("Index","ThongTinCaNhan")">Thông tin cá nhân</a>
                            <a class="dropdown-item" href="@Url.Action("Logout","DangNhap")">Đăng xuất</a>
                        </div>
                    </li>

                    <li class="nav-item cta cta-colored"><a href="@Url.Action("Index","GioHang")" class="nav-link"><span class="icon-shopping_cart"></span>[0]</a></li>

                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()

    <footer class="ftco-footer ftco-section">
        <div class="container">
            <div class="row">
                <div class="mouse">
                    <a href="#" class="mouse-icon">
                        <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                    </a>
                </div>
            </div>
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Bầu Bí</h2>
                        <p>Hương vị quê nhà.</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Mục lục</h2>
                        <div class="d-flex">
                            <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                                <li><a href="@Url.Action("Index", "Home")" class="py-2 d-block">Trang chủ</a></li>
                                <li><a href="@Url.Action("Index","MenuSanPham")" class="py-2 d-block">Menu sản phẩm</a></li>
                                <li><a href="@Url.Action("Index","GioHang")" class="py-2 d-block">Giỏ hàng</a></li>
                                <li><a href="@Url.Action("Index","DonDatHangCuaToi",new {id=1})" class="py-2 d-block">Đơn hàng của tôi</a></li>
                            </ul>
                            <ul class="list-unstyled">
                                <li><a href="@Url.Action("Index","GioiThieu")" class="py-2 d-block">Giới thiệu</a></li>
                                <li><a href="@Url.Action("Index","ThongTinCaNhan")" class="py-2 d-block">Thông tin cá nhân</a></li>
                                <li><a href="@Url.Action("Logout","DangNhap")" class="py-2 d-block">Đăng xuất</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Liên hệ</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker"></span><span class="text">24/47 đường 621, KP6, P.Linh Trung, Q.Thủ Đức, TP.Hồ Chí Minh.</span></li>
                                <li><a href="#"><span class="icon icon-phone"></span><span class="text">093 8099 440</span></a></li>
                                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">quancombaubi@gmail.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">

                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>



    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>


    <script src="~/Assets/khachhang/js/jquery.min.js"></script>
    <script src="~/Assets/khachhang/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/Assets/khachhang/js/popper.min.js"></script>
    <script src="~/Assets/khachhang/js/bootstrap.min.js"></script>
    <script src="~/Assets/khachhang/js/jquery.easing.1.3.js"></script>
    <script src="~/Assets/khachhang/js/jquery.waypoints.min.js"></script>
    <script src="~/Assets/khachhang/js/jquery.stellar.min.js"></script>
    <script src="~/Assets/khachhang/js/owl.carousel.min.js"></script>
    <script src="~/Assets/khachhang/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Assets/khachhang/js/aos.js"></script>
    <script src="~/Assets/khachhang/js/jquery.animateNumber.min.js"></script>
    <script src="~/Assets/khachhang/js/bootstrap-datepicker.js"></script>
    <script src="~/Assets/khachhang/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/Assets/khachhang/js/google-map.js"></script>
    <script src="~/Assets/khachhang/js/main.js"></script>

</body>
</html>